/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/staging/errored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Errored */
        get: operations["list_errored_api_staging_errored_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Staging Row */
        get: operations["get_staging_row_api_staging__row_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/{row_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Staging Row */
        post: operations["correct_staging_row_api_staging__row_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/shipping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shipping Jobs */
        get: operations["list_shipping_jobs_api_jobs_shipping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job History */
        get: operations["list_job_history_api_jobs_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Lineage */
        get: operations["get_job_lineage_api_jobs__job_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assemblies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assemblies */
        get: operations["list_assemblies_api_assemblies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assemblies/{assembly_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assembly */
        get: operations["get_assembly_api_assemblies__assembly_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assemblies/{assembly_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assembly Jobs */
        get: operations["get_assembly_jobs_api_assemblies__assembly_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Upload */
        post: operations["ingest_upload_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssemblyRead */
        AssemblyRead: {
            /** Part Number */
            part_number: string;
            /** Program Name */
            program_name?: string | null;
            /** Smt Placements */
            smt_placements?: number | null;
            /**
             * Base Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_pcb_notes?: string | null;
            /**
             * Base Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_mfg_notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Classifications */
            classifications?: components["schemas"]["ClassificationRead"][];
        };
        /** AssemblyWithJobs */
        AssemblyWithJobs: {
            /** Part Number */
            part_number: string;
            /** Program Name */
            program_name?: string | null;
            /** Smt Placements */
            smt_placements?: number | null;
            /**
             * Base Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_pcb_notes?: string | null;
            /**
             * Base Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_mfg_notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Classifications */
            classifications?: components["schemas"]["ClassificationRead"][];
            /** Jobs */
            jobs?: components["schemas"]["JobRead"][];
        };
        /** Body_ingest_upload_api_ingest_post */
        Body_ingest_upload_api_ingest_post: {
            /**
             * File
             * @description Excel workbook (.xlsx) to ingest
             */
            file: string;
        };
        /**
         * BuildType
         * @enum {string}
         */
        BuildType: "new" | "ronc" | "rowc";
        /**
         * BuildQualifier
         * @enum {string}
         */
        BuildQualifier: "rwk" | "rework" | "rma";
        /** ClassificationRead */
        ClassificationRead: {
            /** Code */
            code: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CustomerRead */
        CustomerRead: {
            /** Name */
            name: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportStagingRowRead */
        ImportStagingRowRead: {
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Source Row Number */
            source_row_number: number;
            processing_status: components["schemas"]["ImportStatus"];
            /** Processing Error */
            processing_error: string | null;
            /** Suggested Correction */
            suggested_correction: string | null;
            /** Resolved Job Id */
            resolved_job_id: number | null;
            /** Processed At */
            processed_at: string | null;
            /** Discarded At */
            discarded_at?: string | null;
            /** Duplicate Group Key */
            duplicate_group_key?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ConflictKind
         * @enum {string}
         */
        ConflictKind: "intra_file_duplicate";
        /** ConflictGroup */
        ConflictGroup: {
            /** Batch Id */
            batch_id: number;
            /** Group Key */
            group_key: string;
            kind: components["schemas"]["ConflictKind"];
            /** Rows (StagingRowDetailRead, len >= 2) */
            rows: components["schemas"]["StagingRowDetailRead"][];
        };
        /**
         * ImportStatus
         * @enum {string}
         */
        ImportStatus: "pending" | "processed" | "error";
        /** JobRead */
        JobRead: {
            /** Assembly Id */
            assembly_id: number;
            /** Customer Id */
            customer_id: number;
            /** Salesperson Id */
            salesperson_id?: number | null;
            /** Split Suffix */
            split_suffix?: string | null;
            /** Repeat Reference */
            repeat_reference?: string | null;
            build_type?: components["schemas"]["BuildType"] | null;
            /** @default planned */
            status: components["schemas"]["JobStatus"];
            /** Quantity */
            quantity: number;
            /** Ship Date Text */
            ship_date_text?: string | null;
            /** Ship Lead Time Raw */
            ship_lead_time_raw?: string | null;
            /** Resolved Ship Date */
            resolved_ship_date?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Ship Method */
            ship_method?: string | null;
            /** Smt Feeder Count */
            smt_feeder_count?: number | null;
            /** Doc Released At */
            doc_released_at?: string | null;
            /** Kit Released At */
            kit_released_at?: string | null;
            /** Wip Status Note */
            wip_status_note?: string | null;
            /** Wip Expected Clear Date */
            wip_expected_clear_date?: string | null;
            /** Notes Clear Date Raw */
            notes_clear_date_raw?: string | null;
            /** Run Cost */
            run_cost?: number | null;
            /** Bom Compare Photos */
            bom_compare_photos?: string | null;
            /**
             * Run Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_pcb_notes?: string | null;
            /**
             * Run Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_mfg_notes?: string | null;
            /**
             * Kit Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            kit_notes?: string | null;
            /**
             * Scheduling Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            scheduling_notes?: string | null;
            /**
             * Line 1
             * @default false
             */
            line_1: boolean;
            /**
             * Line 2
             * @default false
             */
            line_2: boolean;
            /**
             * Line 3
             * @default false
             */
            line_3: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** JobReadExpanded */
        JobReadExpanded: {
            /** Assembly Id */
            assembly_id: number;
            /** Customer Id */
            customer_id: number;
            /** Salesperson Id */
            salesperson_id?: number | null;
            /** Split Suffix */
            split_suffix?: string | null;
            /** Repeat Reference */
            repeat_reference?: string | null;
            build_type?: components["schemas"]["BuildType"] | null;
            /** @default planned */
            status: components["schemas"]["JobStatus"];
            /** Quantity */
            quantity: number;
            /** Ship Date Text */
            ship_date_text?: string | null;
            /** Ship Lead Time Raw */
            ship_lead_time_raw?: string | null;
            /** Resolved Ship Date */
            resolved_ship_date?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Ship Method */
            ship_method?: string | null;
            /** Smt Feeder Count */
            smt_feeder_count?: number | null;
            /** Doc Released At */
            doc_released_at?: string | null;
            /** Kit Released At */
            kit_released_at?: string | null;
            /** Wip Status Note */
            wip_status_note?: string | null;
            /** Wip Expected Clear Date */
            wip_expected_clear_date?: string | null;
            /** Notes Clear Date Raw */
            notes_clear_date_raw?: string | null;
            /** Run Cost */
            run_cost?: number | null;
            /** Bom Compare Photos */
            bom_compare_photos?: string | null;
            /**
             * Run Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_pcb_notes?: string | null;
            /**
             * Run Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_mfg_notes?: string | null;
            /**
             * Kit Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            kit_notes?: string | null;
            /**
             * Scheduling Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            scheduling_notes?: string | null;
            /**
             * Line 1
             * @default false
             */
            line_1: boolean;
            /**
             * Line 2
             * @default false
             */
            line_2: boolean;
            /**
             * Line 3
             * @default false
             */
            line_3: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            assembly: components["schemas"]["AssemblyRead"];
            customer: components["schemas"]["CustomerRead"];
            salesperson?: components["schemas"]["SalespersonRead"] | null;
            build_qualifier?: components["schemas"]["BuildQualifier"] | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "planned" | "wip" | "shipped";
        /** SalespersonRead */
        SalespersonRead: {
            /** Code */
            code: string;
            /** Name */
            name?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** StagingRowCorrectionRequest */
        StagingRowCorrectionRequest: {
            /** Raw Shipped */
            raw_shipped?: string | null;
            /** Raw Pcb Notes */
            raw_pcb_notes?: string | null;
            /** Raw Kit Notes */
            raw_kit_notes?: string | null;
            /** Raw Scheduling Notes */
            raw_scheduling_notes?: string | null;
            /** Raw Line 1 */
            raw_line_1?: string | null;
            /** Raw Line 2 */
            raw_line_2?: string | null;
            /** Raw Line 3 */
            raw_line_3?: string | null;
            /** Raw Job */
            raw_job?: string | null;
            /** Raw Qty */
            raw_qty?: string | null;
            /** Raw Ship Date */
            raw_ship_date?: string | null;
            /** Raw Prog */
            raw_prog?: string | null;
            /** Raw Mfg Notes */
            raw_mfg_notes?: string | null;
            /** Raw Smt Lines */
            raw_smt_lines?: string | null;
            /** Raw Smt Plcmnts */
            raw_smt_plcmnts?: string | null;
            /** Raw Ship Method */
            raw_ship_method?: string | null;
            /** Raw Customer */
            raw_customer?: string | null;
            /** Raw Sales P */
            raw_sales_p?: string | null;
            /** Raw Doc Rel */
            raw_doc_rel?: string | null;
            /** Raw Kit Rel */
            raw_kit_rel?: string | null;
            /** Raw Code */
            raw_code?: string | null;
            /** Raw Bom Compare Photos */
            raw_bom_compare_photos?: string | null;
        };
        /** StagingRowDetailRead */
        StagingRowDetailRead: {
            /** Raw Shipped */
            raw_shipped?: string | null;
            /** Raw Pcb Notes */
            raw_pcb_notes?: string | null;
            /** Raw Kit Notes */
            raw_kit_notes?: string | null;
            /** Raw Scheduling Notes */
            raw_scheduling_notes?: string | null;
            /** Raw Line 1 */
            raw_line_1?: string | null;
            /** Raw Line 2 */
            raw_line_2?: string | null;
            /** Raw Line 3 */
            raw_line_3?: string | null;
            /** Raw Job */
            raw_job?: string | null;
            /** Raw Qty */
            raw_qty?: string | null;
            /** Raw Ship Date */
            raw_ship_date?: string | null;
            /** Raw Prog */
            raw_prog?: string | null;
            /** Raw Mfg Notes */
            raw_mfg_notes?: string | null;
            /** Raw Smt Lines */
            raw_smt_lines?: string | null;
            /** Raw Smt Plcmnts */
            raw_smt_plcmnts?: string | null;
            /** Raw Ship Method */
            raw_ship_method?: string | null;
            /** Raw Customer */
            raw_customer?: string | null;
            /** Raw Sales P */
            raw_sales_p?: string | null;
            /** Raw Doc Rel */
            raw_doc_rel?: string | null;
            /** Raw Kit Rel */
            raw_kit_rel?: string | null;
            /** Raw Code */
            raw_code?: string | null;
            /** Raw Bom Compare Photos */
            raw_bom_compare_photos?: string | null;
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Source Row Number */
            source_row_number: number;
            processing_status: components["schemas"]["ImportStatus"];
            /** Processing Error */
            processing_error: string | null;
            /** Suggested Correction */
            suggested_correction: string | null;
            /** Resolved Job Id */
            resolved_job_id: number | null;
            /** Processed At */
            processed_at: string | null;
            /** Discarded At */
            discarded_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Highlight Fields */
            readonly highlight_fields: string[];
            build_qualifier?: components["schemas"]["BuildQualifier"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_errored_api_staging_errored_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStagingRowRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staging_row_api_staging__row_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagingRowDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_staging_row_api_staging__row_id__correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StagingRowCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                assembly_id?: number | null;
                customer_id?: number | null;
                build_type?: components["schemas"]["BuildType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shipping_jobs_api_jobs_shipping_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_history_api_jobs_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_lineage_api_jobs__job_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assemblies_api_assemblies_get: {
        parameters: {
            query?: {
                customer_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assembly_api_assemblies__assembly_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assembly_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assembly_jobs_api_assemblies__assembly_id__jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                assembly_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyWithJobs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_upload_api_ingest_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_upload_api_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
