/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/staging/conflicts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conflicts */
        get: operations["list_conflicts_api_staging_conflicts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/errored": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Errored */
        get: operations["list_errored_api_staging_errored_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/discarded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Discarded */
        get: operations["list_discarded_api_staging_discarded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/{row_id}/restore-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Restore Preview */
        get: operations["get_restore_preview_api_staging__row_id__restore_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Staging Row */
        get: operations["get_staging_row_api_staging__row_id__get"];
        put?: never;
        post?: never;
        /** Discard Staging Row */
        delete: operations["discard_staging_row_api_staging__row_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/{row_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore Staging Row */
        post: operations["restore_staging_row_api_staging__row_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/staging/{row_id}/correct": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Correct Staging Row */
        post: operations["correct_staging_row_api_staging__row_id__correct_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/shipping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Shipping Jobs */
        get: operations["list_shipping_jobs_api_jobs_shipping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Job History */
        get: operations["list_job_history_api_jobs_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/history/export-columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History Export Columns */
        get: operations["list_history_export_columns_api_jobs_history_export_columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/history/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export History Csv */
        get: operations["export_history_csv_api_jobs_history_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/discarded": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Discarded Jobs */
        get: operations["list_discarded_jobs_api_jobs_discarded_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/second-ops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Second Ops
         * @description Return the complete 2nd OPS record for a job.
         *
         *     200 with the full line set ordered by line_order, plus the limits block.
         *     200 with state "unaudited" and empty lines for a job never audited —
         *         absence of a record is not 404.
         *     200 for discarded, superseded and shipped jobs: reads are not guarded by
         *         status, only writes are.
         *     404 only when the job itself does not exist.
         */
        get: operations["get_job_second_ops_api_jobs__job_id__second_ops_get"];
        /**
         * Put Job Second Ops
         * @description Replace the entire 2nd OPS record for a job. Whole-set replace, not a merge.
         *
         *     PUT rather than POST: this is an idempotent whole-set replace of a
         *     sub-resource.
         *
         *     Writes are restricted to planned, non-discarded, non-superseded jobs.
         *     Concurrency is last-write-wins — there is no version token.
         *
         *     200 with the refreshed record.
         *     404 if the job does not exist.
         *     409 { kind } if the job is discarded, superseded or shipped.
         *     422 { field, message } if a Settings-derived bound is exceeded.
         *     422 (Pydantic) if a line field exceeds its column width.
         *     500 { kind: "storage" } if the delete or insert raised a database error;
         *         nothing is written and the prior line set survives.
         */
        put: operations["put_job_second_ops_api_jobs__job_id__second_ops_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Lineage */
        get: operations["get_job_lineage_api_jobs__job_id__lineage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Discard Job
         * @description Soft-delete a job by setting discarded_at.
         *
         *     Returns the soft-deleted job on success.
         *     404 if the job does not exist.
         *     409 if the job is already discarded (body contains the existing row).
         */
        post: operations["discard_job_api_jobs__job_id__discard_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/restore-preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Restore Preview
         * @description Return a conflict-preview snapshot for a discarded job.
         *
         *     404 if the job does not exist.
         *     409 if the job is not currently discarded.
         */
        get: operations["get_job_restore_preview_api_jobs__job_id__restore_preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore Job
         * @description Restore a discarded job, applying staging-side resolution actions atomically.
         *
         *     404 if the job does not exist.
         *     409 if the job is not currently discarded.
         *     409 with body { detail, preview } on residual collision after actions.
         *     422 with body { detail, action_index } on per-action validation failure.
         */
        post: operations["restore_job_api_jobs__job_id__restore_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/history-edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Edit History Job
         * @description Edit reconciliation-style fields of a shipped job.
         *
         *     404 if job not found.
         *     409 if not shipped or already discarded (body: { kind }).
         *     409 if the edit would create an identity collision
         *         (body: { message, colliding_job_id }).
         *     422 with body { field, message } on per-field parse failure.
         *     422 (Pydantic) if no raw_* field was provided.
         */
        patch: operations["edit_history_job_api_jobs__job_id__history_edit_patch"];
        trace?: never;
    };
    "/api/assemblies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Assemblies */
        get: operations["list_assemblies_api_assemblies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assemblies/{assembly_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assembly */
        get: operations["get_assembly_api_assemblies__assembly_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assemblies/{assembly_id}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assembly Jobs */
        get: operations["get_assembly_jobs_api_assemblies__assembly_id__jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ingest Upload */
        post: operations["ingest_upload_api_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/awaiting-review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Awaiting Review
         * @description Return up to 50 batches currently in awaiting_review status, newest first.
         */
        get: operations["list_awaiting_review_api_ingest_awaiting_review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{batch_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Review Payload
         * @description Return the full review payload for a held batch.
         */
        get: operations["get_review_payload_api_ingest__batch_id__review_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{batch_id}/canonical/{parsed_part_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Canonical
         * @description Apply a canonical part_number override to all non-deleted rows in a group.
         */
        put: operations["set_canonical_api_ingest__batch_id__canonical__parsed_part_number__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{batch_id}/staging-row/{row_id}/split-suffix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Split Suffix
         * @description Override the split_suffix on a specific staging row.
         */
        patch: operations["patch_split_suffix_api_ingest__batch_id__staging_row__row_id__split_suffix_patch"];
        trace?: never;
    };
    "/api/ingest/{batch_id}/staging-row/{row_id}/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify Staging Row
         * @description Mark a pending review row as verified (operator confirms parsed value is correct).
         */
        post: operations["verify_staging_row_api_ingest__batch_id__staging_row__row_id__verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{batch_id}/staging-row/{row_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Staging Row From Review
         * @description Hard-discard a staging row during review (D3).  Excluded from Stage 4..6.
         */
        delete: operations["delete_staging_row_from_review_api_ingest__batch_id__staging_row__row_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{batch_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Review
         * @description Run Stage 4..6 against the surviving staging rows and finalize the batch.
         */
        post: operations["confirm_review_api_ingest__batch_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ingest/{batch_id}/abandon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Abandon Review
         * @description Abandon a held batch.  Staging rows are retained for forensics.
         *
         *     After abandonment, the same sha256 file can be re-uploaded because Stage 1
         *     excludes abandoned batches from the duplicate guard (§6.6).
         */
        post: operations["abandon_review_api_ingest__batch_id__abandon_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssemblyRead */
        AssemblyRead: {
            /** Part Number */
            part_number: string;
            /** Program Name */
            program_name?: string | null;
            /** Smt Placements */
            smt_placements?: number | null;
            /**
             * Base Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_pcb_notes?: string | null;
            /**
             * Base Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_mfg_notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Classifications */
            classifications?: components["schemas"]["ClassificationRead"][];
        };
        /** AssemblyWithJobs */
        AssemblyWithJobs: {
            /** Part Number */
            part_number: string;
            /** Program Name */
            program_name?: string | null;
            /** Smt Placements */
            smt_placements?: number | null;
            /**
             * Base Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_pcb_notes?: string | null;
            /**
             * Base Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            base_mfg_notes?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Classifications */
            classifications?: components["schemas"]["ClassificationRead"][];
            /** Jobs */
            jobs?: components["schemas"]["JobRead"][];
        };
        /**
         * AuditBomFields
         * @description The eight retained Audit BOM fields, and nothing else.
         *
         *     Shared by saved rows, unsaved parsed rows and the read-only detail modal, so
         *     a row does not have to be persisted to be displayable.
         *
         *     The max_lengths ARE the §2.2 column widths — one declaration, not two.
         *     Declaring them here is what makes the write path's per-field enforcement
         *     automatic: SecondOpsWriteRequest carries these same models.
         *
         *     Values are stored verbatim — no trim, no case change, no numeric coercion.
         *     Leading spaces in a pasted description are part of what the operator
         *     transcribed.
         */
        AuditBomFields: {
            /** Find Number */
            find_number?: string | null;
            /** Component Part Number */
            component_part_number?: string | null;
            /** Per Board Count */
            per_board_count?: string | null;
            /** Ref Des */
            ref_des?: string | null;
            /** Description */
            description?: string | null;
            /** Mount Type */
            mount_type?: string | null;
            /** Quantity Needed */
            quantity_needed?: string | null;
            /** Quantity On Hand */
            quantity_on_hand?: string | null;
        };
        /** Body_ingest_upload_api_ingest_post */
        Body_ingest_upload_api_ingest_post: {
            /**
             * File
             * @description Excel workbook (.xlsx) to ingest
             */
            file: string;
        };
        /**
         * BuildQualifier
         * @description Suffix-grade work-class qualifier (TDD §3.1.1).
         *
         *     Pre:  raw cell line matches /^(RWK|REWORK|RMA)/i.
         *     Post: cardinality is 3, bounded by business intent.
         *     Note: independent dimension from split_suffix; co-exists with BuildType.
         * @enum {string}
         */
        BuildQualifier: "rwk" | "rework" | "rma";
        /**
         * BuildType
         * @enum {string}
         */
        BuildType: "new" | "ronc" | "rowc";
        /** ClassificationRead */
        ClassificationRead: {
            /** Code */
            code: string;
            /** Description */
            description?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ConflictGroup */
        ConflictGroup: {
            /** Batch Id */
            batch_id: number;
            /** Group Key */
            group_key: string;
            kind: components["schemas"]["ConflictKind"];
            /** Rows */
            rows: components["schemas"]["StagingRowDetailRead"][];
        };
        /**
         * ConflictKind
         * @enum {string}
         */
        ConflictKind: "intra_file_duplicate";
        /** CustomerRead */
        CustomerRead: {
            /** Name */
            name: string;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HistoryJobEditRequest
         * @description Edit reconciliation-style fields of a shipped job.
         *
         *     Five discrete identity fields replace the old raw_job free-text field (Patch 01).
         *     Three ship-time fields retain Phase 17 semantics (is-not-None check; empty rejected).
         *     At least one editable field must be present in the request body; a body containing
         *     only `reason` is rejected (422) by the model validator.
         *
         *     extra="forbid": stale clients that still send the removed `raw_job` key receive an
         *     explicit "extra fields not permitted" 422 rather than a silent drop.
         */
        HistoryJobEditRequest: {
            /** Part Number */
            part_number?: string | null;
            /** Build Type */
            build_type?: string | null;
            /** Split Suffix */
            split_suffix?: string | null;
            /** Repeat Reference */
            repeat_reference?: string | null;
            /** Build Qualifier */
            build_qualifier?: string | null;
            /** Raw Qty */
            raw_qty?: string | null;
            /** Raw Customer */
            raw_customer?: string | null;
            /** Raw Shipped */
            raw_shipped?: string | null;
            /** Reason */
            reason: string;
        };
        /** ImportStagingRowRead */
        ImportStagingRowRead: {
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Source Row Number */
            source_row_number: number;
            processing_status: components["schemas"]["ImportStatus"];
            /** Processing Error */
            processing_error: string | null;
            /** Suggested Correction */
            suggested_correction: string | null;
            /** Resolved Job Id */
            resolved_job_id: number | null;
            /** Processed At */
            processed_at: string | null;
            /** Discarded At */
            discarded_at?: string | null;
            /** Duplicate Group Key */
            duplicate_group_key?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ImportStatus
         * @enum {string}
         */
        ImportStatus: "pending" | "processed" | "error" | "awaiting_review" | "abandoned";
        /**
         * IncomingRestoreCandidate
         * @description The row the operator wants to restore, discriminated by source kind.
         */
        IncomingRestoreCandidate: {
            kind: components["schemas"]["RestoreSourceKind"];
            staging?: components["schemas"]["StagingRowDetailRead"] | null;
            job?: components["schemas"]["JobReadExpanded"] | null;
        };
        /**
         * JobDiscardRequest
         * @description Request body for POST /api/jobs/{jobId}/discard.
         *
         *     `reason` is required (min 1, max 500 chars), written to logger.info,
         *     and not persisted.
         */
        JobDiscardRequest: {
            /** Reason */
            reason: string;
        };
        /** JobRead */
        JobRead: {
            /** Assembly Id */
            assembly_id: number;
            /** Customer Id */
            customer_id: number;
            /** Salesperson Id */
            salesperson_id?: number | null;
            /** Split Suffix */
            split_suffix?: string | null;
            /** Repeat Reference */
            repeat_reference?: string | null;
            build_type?: components["schemas"]["BuildType"] | null;
            /** @default planned */
            status: components["schemas"]["JobStatus"];
            /** Quantity */
            quantity: number;
            /** Ship Date Text */
            ship_date_text?: string | null;
            /** Ship Lead Time Raw */
            ship_lead_time_raw?: string | null;
            /** Resolved Ship Date */
            resolved_ship_date?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Ship Method */
            ship_method?: string | null;
            /** Smt Feeder Count */
            smt_feeder_count?: number | null;
            /** Doc Released At */
            doc_released_at?: string | null;
            /** Kit Released At */
            kit_released_at?: string | null;
            /** Notes Clear Date Raw */
            notes_clear_date_raw?: string | null;
            /** Run Cost */
            run_cost?: number | null;
            /** Bom Compare Photos */
            bom_compare_photos?: string | null;
            /**
             * Run Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_pcb_notes?: string | null;
            /**
             * Run Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_mfg_notes?: string | null;
            /**
             * Kit Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            kit_notes?: string | null;
            /**
             * Scheduling Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            scheduling_notes?: string | null;
            /**
             * Line 1
             * @default false
             */
            line_1: boolean;
            /**
             * Line 2
             * @default false
             */
            line_2: boolean;
            /**
             * Line 3
             * @default false
             */
            line_3: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Discarded At */
            discarded_at?: string | null;
        };
        /** JobReadExpanded */
        JobReadExpanded: {
            /** Assembly Id */
            assembly_id: number;
            /** Customer Id */
            customer_id: number;
            /** Salesperson Id */
            salesperson_id?: number | null;
            /** Split Suffix */
            split_suffix?: string | null;
            /** Repeat Reference */
            repeat_reference?: string | null;
            build_type?: components["schemas"]["BuildType"] | null;
            /** @default planned */
            status: components["schemas"]["JobStatus"];
            /** Quantity */
            quantity: number;
            /** Ship Date Text */
            ship_date_text?: string | null;
            /** Ship Lead Time Raw */
            ship_lead_time_raw?: string | null;
            /** Resolved Ship Date */
            resolved_ship_date?: string | null;
            /** Shipped At */
            shipped_at?: string | null;
            /** Ship Method */
            ship_method?: string | null;
            /** Smt Feeder Count */
            smt_feeder_count?: number | null;
            /** Doc Released At */
            doc_released_at?: string | null;
            /** Kit Released At */
            kit_released_at?: string | null;
            /** Notes Clear Date Raw */
            notes_clear_date_raw?: string | null;
            /** Run Cost */
            run_cost?: number | null;
            /** Bom Compare Photos */
            bom_compare_photos?: string | null;
            /**
             * Run Pcb Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_pcb_notes?: string | null;
            /**
             * Run Mfg Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            run_mfg_notes?: string | null;
            /**
             * Kit Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            kit_notes?: string | null;
            /**
             * Scheduling Notes
             * @description CommonMark-annotated Markdown. Client must render via a Markdown library (e.g. marked).
             */
            scheduling_notes?: string | null;
            /**
             * Line 1
             * @default false
             */
            line_1: boolean;
            /**
             * Line 2
             * @default false
             */
            line_2: boolean;
            /**
             * Line 3
             * @default false
             */
            line_3: boolean;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Discarded At */
            discarded_at?: string | null;
            assembly: components["schemas"]["AssemblyRead"];
            customer: components["schemas"]["CustomerRead"];
            salesperson?: components["schemas"]["SalespersonRead"] | null;
            build_qualifier?: components["schemas"]["BuildQualifier"] | null;
            second_ops?: components["schemas"]["SecondOpsSummary"] | null;
        };
        /**
         * JobRestoreRequest
         * @description Request body for POST /api/jobs/{jobId}/restore.
         *
         *     Symmetric with StagingRestoreRequest (§6.2). Every action references a
         *     staging row id (the operator cannot edit live-job colliders).
         *     `actions: []` is the no-conflict path — restore is attempted directly.
         */
        JobRestoreRequest: {
            /** Actions */
            actions?: components["schemas"]["StagingRestoreAction"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "planned" | "shipped";
        /**
         * RestoreConflictPreview
         * @description Read-only snapshot describing what would collide if a discarded row were restored.
         *
         *     Pre:  the target row exists and discarded_at IS NOT NULL.
         *     Post: purely descriptive — calling the preview endpoint never mutates state.
         */
        RestoreConflictPreview: {
            incoming: components["schemas"]["IncomingRestoreCandidate"];
            /** Colliding Staging Errored Rows */
            colliding_staging_errored_rows: components["schemas"]["StagingRowDetailRead"][];
            /** Colliding Staging Discarded Rows */
            colliding_staging_discarded_rows: components["schemas"]["StagingRowDetailRead"][];
            /** Colliding Live Jobs */
            colliding_live_jobs: components["schemas"]["JobReadExpanded"][];
            /** Group Key */
            group_key: string;
        };
        /**
         * RestoreSourceKind
         * @description Discriminates whether a restore candidate is a staging row or a persisted job.
         * @enum {string}
         */
        RestoreSourceKind: "staging" | "job";
        /** SalespersonRead */
        SalespersonRead: {
            /** Code */
            code: string;
            /** Name */
            name?: string | null;
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SecondOpsLimits
         * @description Server-owned input bounds, echoed to the client so it never hardcodes one.
         *
         *     Delivered on the record read rather than a separate settings endpoint: the
         *     entry modal already fetches the record on open and has nowhere else to learn
         *     the caps. A client-side constant drifts the moment an operator changes
         *     second_ops_max_lines — pastes between the two numbers would pass the local
         *     guard and come back 422 with no line number.
         */
        SecondOpsLimits: {
            /** Max Lines */
            max_lines: number;
            /** Note Max Chars */
            note_max_chars: number;
        };
        /**
         * SecondOpsLine
         * @description A persisted line: the eight fields plus its identity and position.
         */
        SecondOpsLine: {
            /** Find Number */
            find_number?: string | null;
            /** Component Part Number */
            component_part_number?: string | null;
            /** Per Board Count */
            per_board_count?: string | null;
            /** Ref Des */
            ref_des?: string | null;
            /** Description */
            description?: string | null;
            /** Mount Type */
            mount_type?: string | null;
            /** Quantity Needed */
            quantity_needed?: string | null;
            /** Quantity On Hand */
            quantity_on_hand?: string | null;
            /** Id */
            id: number;
            /** Line Order */
            line_order: number;
        };
        /**
         * SecondOpsRecord
         * @description The complete 2nd OPS record for one job, unbounded by the preview cap.
         */
        SecondOpsRecord: {
            /** Job Id */
            job_id: number;
            /**
             * State
             * @enum {string}
             */
            state: "unaudited" | "not_applicable" | "recorded";
            /** Reviewed At */
            reviewed_at?: string | null;
            /** Unexpected Inclusions */
            unexpected_inclusions?: string | null;
            /** Lines */
            lines?: components["schemas"]["SecondOpsLine"][];
            limits: components["schemas"]["SecondOpsLimits"];
        };
        /**
         * SecondOpsSummary
         * @description Bounded per-job summary carried by the two grid endpoints.
         *
         *     preview carries WHOLE lines, not a narrowed projection: the item modal
         *     renders all eight fields and opening it from a grid cell must not need a
         *     second fetch. The cell still renders only three of them.
         */
        SecondOpsSummary: {
            /**
             * State
             * @enum {string}
             */
            state: "unaudited" | "not_applicable" | "recorded";
            /** Line Count */
            line_count: number;
            /** Reviewed At */
            reviewed_at?: string | null;
            /**
             * Has Unexpected Inclusions
             * @default false
             */
            has_unexpected_inclusions: boolean;
            /** Preview */
            preview?: components["schemas"]["SecondOpsLine"][];
        };
        /**
         * SecondOpsWriteRequest
         * @description Whole-set replace payload for PUT /api/jobs/{job_id}/second-ops.
         *
         *     The client parses the paste and maps the columns; the server trusts neither.
         *     Per-field widths are enforced here by AuditBomFields. The line count and the
         *     note length are bounded by Settings and checked in
         *     validate_second_ops_payload, because both are operator-configurable.
         */
        SecondOpsWriteRequest: {
            /** Lines */
            lines?: components["schemas"]["AuditBomFields"][];
            /** Unexpected Inclusions */
            unexpected_inclusions?: string | null;
        };
        /**
         * StagingRestoreAction
         * @description One operator-resolution action for a staging-side row in the preview modal.
         */
        StagingRestoreAction: {
            /** Kind */
            kind: string;
            /** Row Id */
            row_id: number;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * StagingRestoreRequest
         * @description Request body for POST /api/staging/{rowId}/restore.
         *
         *     `actions: []` is the no-conflict path — restore is attempted directly.
         */
        StagingRestoreRequest: {
            /** Actions */
            actions?: components["schemas"]["StagingRestoreAction"][];
        };
        /** StagingRowCorrectionRequest */
        StagingRowCorrectionRequest: {
            /** Raw Shipped */
            raw_shipped?: string | null;
            /** Raw Pcb Notes */
            raw_pcb_notes?: string | null;
            /** Raw Kit Notes */
            raw_kit_notes?: string | null;
            /** Raw Scheduling Notes */
            raw_scheduling_notes?: string | null;
            /** Raw Line 1 */
            raw_line_1?: string | null;
            /** Raw Line 2 */
            raw_line_2?: string | null;
            /** Raw Line 3 */
            raw_line_3?: string | null;
            /** Raw Job */
            raw_job?: string | null;
            /** Raw Qty */
            raw_qty?: string | null;
            /** Raw Ship Date */
            raw_ship_date?: string | null;
            /** Raw Prog */
            raw_prog?: string | null;
            /** Raw Mfg Notes */
            raw_mfg_notes?: string | null;
            /** Raw Smt Lines */
            raw_smt_lines?: string | null;
            /** Raw Smt Plcmnts */
            raw_smt_plcmnts?: string | null;
            /** Raw Ship Method */
            raw_ship_method?: string | null;
            /** Raw Customer */
            raw_customer?: string | null;
            /** Raw Sales P */
            raw_sales_p?: string | null;
            /** Raw Doc Rel */
            raw_doc_rel?: string | null;
            /** Raw Kit Rel */
            raw_kit_rel?: string | null;
            /** Raw Code */
            raw_code?: string | null;
            /** Raw Bom Compare Photos */
            raw_bom_compare_photos?: string | null;
        };
        /** StagingRowDetailRead */
        StagingRowDetailRead: {
            /** Raw Shipped */
            raw_shipped?: string | null;
            /** Raw Pcb Notes */
            raw_pcb_notes?: string | null;
            /** Raw Kit Notes */
            raw_kit_notes?: string | null;
            /** Raw Scheduling Notes */
            raw_scheduling_notes?: string | null;
            /** Raw Line 1 */
            raw_line_1?: string | null;
            /** Raw Line 2 */
            raw_line_2?: string | null;
            /** Raw Line 3 */
            raw_line_3?: string | null;
            /** Raw Job */
            raw_job?: string | null;
            /** Raw Qty */
            raw_qty?: string | null;
            /** Raw Ship Date */
            raw_ship_date?: string | null;
            /** Raw Prog */
            raw_prog?: string | null;
            /** Raw Mfg Notes */
            raw_mfg_notes?: string | null;
            /** Raw Smt Lines */
            raw_smt_lines?: string | null;
            /** Raw Smt Plcmnts */
            raw_smt_plcmnts?: string | null;
            /** Raw Ship Method */
            raw_ship_method?: string | null;
            /** Raw Customer */
            raw_customer?: string | null;
            /** Raw Sales P */
            raw_sales_p?: string | null;
            /** Raw Doc Rel */
            raw_doc_rel?: string | null;
            /** Raw Kit Rel */
            raw_kit_rel?: string | null;
            /** Raw Code */
            raw_code?: string | null;
            /** Raw Bom Compare Photos */
            raw_bom_compare_photos?: string | null;
            /** Id */
            id: number;
            /** Batch Id */
            batch_id: number;
            /** Source Row Number */
            source_row_number: number;
            processing_status: components["schemas"]["ImportStatus"];
            /** Processing Error */
            processing_error: string | null;
            /** Suggested Correction */
            suggested_correction: string | null;
            /** Resolved Job Id */
            resolved_job_id: number | null;
            /** Processed At */
            processed_at: string | null;
            /** Discarded At */
            discarded_at?: string | null;
            /** Duplicate Group Key */
            duplicate_group_key?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            build_qualifier?: components["schemas"]["BuildQualifier"] | null;
            /** Highlight Fields */
            readonly highlight_fields: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_conflicts_api_staging_conflicts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictGroup"][];
                };
            };
        };
    };
    list_errored_api_staging_errored_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStagingRowRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_discarded_api_staging_discarded_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStagingRowRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_restore_preview_api_staging__row_id__restore_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreConflictPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staging_row_api_staging__row_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StagingRowDetailRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_staging_row_api_staging__row_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_staging_row_api_staging__row_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["StagingRestoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportStagingRowRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_staging_row_api_staging__row_id__correct_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                row_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StagingRowCorrectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
                assembly_id?: number | null;
                customer_id?: number | null;
                build_type?: components["schemas"]["BuildType"] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shipping_jobs_api_jobs_shipping_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_job_history_api_jobs_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_history_export_columns_api_jobs_history_export_columns_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_history_csv_api_jobs_history_export_csv_get: {
        parameters: {
            query: {
                column: string[];
                delimiter: string;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_discarded_jobs_api_jobs_discarded_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_second_ops_api_jobs__job_id__second_ops_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecondOpsRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_job_second_ops_api_jobs__job_id__second_ops_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SecondOpsWriteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecondOpsRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_lineage_api_jobs__job_id__lineage_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    discard_job_api_jobs__job_id__discard_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobDiscardRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_restore_preview_api_jobs__job_id__restore_preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreConflictPreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restore_job_api_jobs__job_id__restore_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JobRestoreRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_history_job_api_jobs__job_id__history_edit_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistoryJobEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobReadExpanded"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assemblies_api_assemblies_get: {
        parameters: {
            query?: {
                customer_id?: number | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assembly_api_assemblies__assembly_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assembly_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assembly_jobs_api_assemblies__assembly_id__jobs_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path: {
                assembly_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssemblyWithJobs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_upload_api_ingest_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_ingest_upload_api_ingest_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_awaiting_review_api_ingest_awaiting_review_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_review_payload_api_ingest__batch_id__review_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_canonical_api_ingest__batch_id__canonical__parsed_part_number__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
                parsed_part_number: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_split_suffix_api_ingest__batch_id__staging_row__row_id__split_suffix_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
                row_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_staging_row_api_ingest__batch_id__staging_row__row_id__verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_staging_row_from_review_api_ingest__batch_id__staging_row__row_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
                row_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_review_api_ingest__batch_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    abandon_review_api_ingest__batch_id__abandon_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
