"""baseline

Revision ID: 0001
Revises: 
Create Date: 2026-04-25 13:37:35.847688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assemblies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=False),
    sa.Column('program_name', sa.String(length=64), nullable=True),
    sa.Column('smt_placements', sa.Integer(), nullable=True),
    sa.Column('base_pcb_notes', sa.Text(), nullable=True),
    sa.Column('base_mfg_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processed', 'error', name='import_batch_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salespeople',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('assembly_classifications',
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('classification_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['classification_id'], ['classifications.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('assembly_id', 'classification_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assembly_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('salesperson_id', sa.Integer(), nullable=True),
    sa.Column('split_suffix', sa.String(length=32), nullable=True),
    sa.Column('repeat_reference', sa.String(length=32), nullable=True),
    sa.Column('build_type', sa.Enum('new', 'ronc', 'rowc', 'rwk', name='build_type'), nullable=True),
    sa.Column('status', sa.Enum('planned', 'wip', 'shipped', name='job_status'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('ship_date_text', sa.String(length=5), nullable=True),
    sa.Column('ship_lead_time_raw', sa.String(length=16), nullable=True),
    sa.Column('resolved_ship_date', sa.Date(), nullable=True),
    sa.Column('shipped_at', sa.Date(), nullable=True),
    sa.Column('ship_method', sa.String(length=64), nullable=True),
    sa.Column('smt_feeder_count', sa.Integer(), nullable=True),
    sa.Column('doc_released_at', sa.Date(), nullable=True),
    sa.Column('kit_released_at', sa.Date(), nullable=True),
    sa.Column('wip_status_note', sa.Text(), nullable=True),
    sa.Column('wip_expected_clear_date', sa.Date(), nullable=True),
    sa.Column('notes_clear_date_raw', sa.String(length=16), nullable=True),
    sa.Column('run_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bom_compare_photos', sa.Text(), nullable=True),
    sa.Column('run_pcb_notes', sa.Text(), nullable=True),
    sa.Column('run_mfg_notes', sa.Text(), nullable=True),
    sa.Column('kit_notes', sa.Text(), nullable=True),
    sa.Column('scheduling_notes', sa.Text(), nullable=True),
    sa.Column('line_1', sa.Boolean(), nullable=False),
    sa.Column('line_2', sa.Boolean(), nullable=False),
    sa.Column('line_3', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assembly_id'], ['assemblies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['salesperson_id'], ['salespeople.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assembly_id', 'build_type', 'split_suffix', 'repeat_reference', name='uq_job_identity')
    )
    op.create_table('import_staging',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('raw_shipped', sa.Text(), nullable=True),
    sa.Column('raw_pcb_notes', sa.Text(), nullable=True),
    sa.Column('raw_kit_notes', sa.Text(), nullable=True),
    sa.Column('raw_scheduling_notes', sa.Text(), nullable=True),
    sa.Column('raw_line_1', sa.Text(), nullable=True),
    sa.Column('raw_line_2', sa.Text(), nullable=True),
    sa.Column('raw_line_3', sa.Text(), nullable=True),
    sa.Column('raw_job', sa.Text(), nullable=True),
    sa.Column('raw_qty', sa.Text(), nullable=True),
    sa.Column('raw_ship_date', sa.Text(), nullable=True),
    sa.Column('raw_prog', sa.Text(), nullable=True),
    sa.Column('raw_mfg_notes', sa.Text(), nullable=True),
    sa.Column('raw_smt_lines', sa.Text(), nullable=True),
    sa.Column('raw_smt_plcmnts', sa.Text(), nullable=True),
    sa.Column('raw_ship_method', sa.Text(), nullable=True),
    sa.Column('raw_customer', sa.Text(), nullable=True),
    sa.Column('raw_sales_p', sa.Text(), nullable=True),
    sa.Column('raw_doc_rel', sa.Text(), nullable=True),
    sa.Column('raw_kit_rel', sa.Text(), nullable=True),
    sa.Column('raw_code', sa.Text(), nullable=True),
    sa.Column('raw_bom_compare_photos', sa.Text(), nullable=True),
    sa.Column('processing_status', sa.Enum('pending', 'processed', 'error', name='import_row_status'), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('suggested_correction', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_job_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_staging', schema=None) as batch_op:
        batch_op.create_index('ix_import_staging_batch_id', ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('import_staging', schema=None) as batch_op:
        batch_op.drop_index('ix_import_staging_batch_id')

    op.drop_table('import_staging')
    op.drop_table('jobs')
    op.drop_table('assembly_classifications')
    op.drop_table('salespeople')
    op.drop_table('import_batches')
    op.drop_table('customers')
    op.drop_table('classifications')
    op.drop_table('assemblies')
    # ### end Alembic commands ###
