"""Add ix_job_active_planned index

Revision ID: 1ccdbd14008f
Revises: 0010
Create Date: 2026-06-03 22:04:59.843432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ccdbd14008f'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_job_active_planned', ['status'], unique=False, sqlite_where=sa.text('superseded_at IS NULL AND discarded_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_job_active_planned', sqlite_where=sa.text('superseded_at IS NULL AND discarded_at IS NULL'))
    # ### end Alembic commands ###
